version: '3.8'

volumes:
  frontvolume:
  api_node_modules:

services:
  vue:
    container_name: vue
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - frontvolume:/app/node_modules
    ports:
      - '5173:5173'

  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - internalnet

  bunapp:
    container_name: bunappcontainer
    build: ./backend
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      SERVER_PORT: ${APP_PORT}
    volumes:
      - ./backend:/app
      - api_node_modules:/app/node_modules
    networks:
      - internalnet

# connection between services
networks:
  internalnet:
    driver: bridge